package errorsexceptions;
import static errorsexceptions.util.Print.*;
import java.util.*;

public class Main {
    public static void main(String[] args) {
	    //InheritingExceptions.main();//Создание собственного исключения

        //FullConstructors.main();//создание класса исключения с конструктором, получающим аргумент String

        //LoggingExceptions.main();//регистрация исключений с использованием Logger

        //LoggingExceptions2.main();//Регистрация перехваченных исключений(перехват и регистрация сторонних исключений, сообзение генерируется в обработчике исключений. Так чаще бывает на практике)

        //ExtraFeatures.main();//Расширение классов исключений

        //ExceptionMethods.main();//Демонстрация методов класса Exception

        //WhoCalled.main();//Программный доступ к данным трассировки стека

        //NeverCaught.main();//игнорирование RuntimeException

        //FinallyWorks.main();//блок finally выполняется всегда

        //OnOffSwitch.main();//пример без finally

        //WithFinally.main();//пример с finally

        //AlwaysFinally.main();//finally выполняется всегда

        //MultipleReturns.main();//finally c return

        //StormyInning.main();//переопределенные методы в исключениях

        //Cleanup.main();//Гарантированное освобождение ресурсов

        //CleanupIdiom.main();//за каждым освобождаемым объектом следует try-finally

        //TurnOffChecking.main();//подавление контролируемых исключений
    }
}
